name: pyml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=2.2.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - cfgv=3.2.0
  - chardet=4.0.0
  - conda=4.10.1
  - conda-package-handling=1.7.3
  - cryptography=3.4.7
  - decorator=5.0.7
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - distlib=0.3.1
  - editdistance-s=1.0.0
  - entrypoints=0.3
  - filelock=3.0.12
  - identify=2.2.3
  - idna=2.10
  - importlib-metadata=3.10.1
  - ipykernel=5.5.3
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.9.1
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.6.2
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbclassic=0.2.7
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nodeenv=1.6.0
  - notebook=6.3.0
  - numpy=1.20.2
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.12
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - pre-commit=2.12.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - ptyprocess=0.7.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - readline=8.0
  - requests=2.25.1
  - ruamel_yaml=0.15.80
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.4
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - tomlkit=0.7.0
  - tornado=6.1
  - tqdm=4.60.0
  - traitlets=5.0.5
  - urllib3=1.26.4
  - virtualenv=20.4.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - pip:
    - aquirdturtle-collapsible-headings==3.0.1
